### ISSUE TITLE
Roadmap for 0.3 release

### ISSUE THREAD

**Issue by aliles** [aliles/begins#2]
From https://github.com/aliles/begins/blob/master/docs/roadmap.rst
- [x] Environment variable parsing does not default to being enabled.
- [x] Use _argparse_ module over _optparse_ internally for command line parsing.
- [x] Remove vendored _funcsigs_ package from within _begin_ package.
- [x] Add external _argparse_ dependency for Python 2.6.
- [x] Add external funcsigs dependency for Python 2.6, 2.7 and 3.2.
