### ISSUE TITLE
Roadmap for 0.5 release

### ISSUE THREAD

**Issue by aliles** [aliles/begins#4]
From https://github.com/aliles/begins/blob/master/docs/roadmap.rst
- [x] Support sub commands using a sub command decorator
  -  _begin.subcommand()_ registers function with a collector.
  - _begin.start()_ checks default collector for registered sub commands.
- [x] Additional collectors may be defined explicitly.
- [x] Load sub commands from setuptools entry points.
